name: Feature request
description: Use this template to submit a feature request
title: "[Feature Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to raise a question
  - type: input
    id: task-name
    attributes:
      label: Task name
  - type: textarea
    id: what-happened
    attributes:
      label: Describe your feature request here
      placeholder: Put your question here.
      description: Please try to provide as much detail as possible
    validations:
      required: true
  - type: select
    id: label-choices
    attributes:
      label: Choose labels
      options:
        - enhancement
        - bug
        - documentation
        - others
    validations:
      required: true
