# This workflow clones issues from GitHub project to Azure DevOps
name: Clone issues to ADO

# Run every hour
on:
  schedule:
   - cron: "0 * * * *"
  workflow_dispatch:
    
jobs:
  clone_ado:
    name: Clone issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      repository-projects: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install azure-devops-node-api@12.0.0
      - uses: actions/github-script@v6
        env:
          adoPat: ${{ secrets.AZP_TOKEN }}
        with:
          github-token: ${{ secrets.RM_AUTO_TEST }}
          script: |
            const script = require('./scripts/clone-issues-to-ado.js');
            const options = {
                gitHubProjectNumber: 3,
                gitHubProjectColumns: ['Ready for work (ordered by priority)', 'In progress'],
                orgUrl: 'https://dev.azure.com/v-mohithgc',
                project: 'AzureDevOps',
                adoPAT: process.env.adoPat,
                workItemType: 'Bug',
                areaPath: 'PM task test\\RMTaskTeam', 
                iteration: 'PM task test\\Sprint 1'
            }
            await script.cloneIssuesToAdo(github, context, options);
