name: Label Selection

on:
  issues:
    types:
      - opened

jobs:
  label_selection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set labels
        id: set_labels
        run: |
          issue_body=$(curl -s -H "Authorization: Bearer ${{ secrets.RM_AUTO_TEST }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" | \
            jq -r '.body')
          
          labels=("Area:RM" "bug" "CG")  # Replace with your available label names
          
          for label in "${labels[@]}"; do
            if [[ $issue_body == *"$label"* ]]; then
              echo "Adding label: $label"
              echo "::set-output name=labels::$label"
            fi
          done

      - name: Add labels
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.RM_AUTO_TEST }}
          script: |
            const labels = core.getInput('labels').split(',');
            const issue = context.payload.issue;
            await github.issues.addLabels({
              owner: issue.owner,
              repo: issue.repo,
              issue_number: issue.number,
              labels: labels
            });
