name: Add Labels Based on Keywords

on:
  issues:
    types:
      - opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Title and Add Labels
        uses: actions/github-script@v4
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();

            // Define your keyword-label mappings
            const keywordLabels = {
              bug: "bug",
              enhancement: "enhancement",
              documentation: "documentation"
            };

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            
            for (const keyword in keywordLabels) {
              if (issueTitle.includes(keyword)) {
                const label = keywordLabels[keyword];
                await octokit.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: [label]
                });
              }
            }
          token: ${{ secrets.RM_AUTO_TEST }}
